version: "3.8"

services:
    live-channels:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        volumes:
            - ./config/config.json:/config/config.json:ro
        environment:
            - CONFIG_PATH=/config/config.json
            - PORT=8081
            - TZ=Asia/Shanghai
            - GIN_MODE=release
            - LOG_LEVEL=info
            # - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
        restart: unless-stopped
        container_name: live-channels
