version: "3.8"

services:
    live-channels:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./config.json:/root/config.json
        environment:
            - TZ=Asia/Shanghai
        restart: unless-stopped
        container_name: live-channels
